{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "apm.fullname" . -}}
{{- $svcPort := 8200 -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "apm.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ $fullName }}-apm-http
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "apm.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: {{ $fullName }}-apm-http
      sectionName: https
  validation:
    caCertificateRefs:
      - group: ''
        kind: Secret
        name: {{ $fullName }}-apm-http-ca-internal
    hostname: {{ $fullName }}-apm-http
{{- end }}
